# Generated by Django 5.0.6 on 2024-07-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_category_item_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
    ]
